### PR TITLE
Putting all text content in an <mtext> node

### PR DESCRIPTION
**Pull request by MMercieca**
This is to produce MathML that MathJax can parse.

### CODE REVIEW

**Comment by bnbeckwith** [comment]
I don't know if this is in scope for this change, but the results don't look complete yet. Looking at the `if``s in the large equation, there is no space around them. This squashes it up agains the variables which is likely not what the author wanted.

Do we also need to add spaces around these `mtext` nodes for legibility?

**Comment by Bestra** [comment]
It'd also be worth adding a spec or two, or at least modifying some of the existing test fixtures to account for the changes.

**Comment by MMercieca** [comment]
We can add &lt;mspace&gt; nodes before and after the text.  The problem is I don't know if we'll always need the space and that could mess up the display of other papers.  We'd really be guessing. 

@bnbeckwith Can you look over the "Custom Spaces" section of http://rypress.com/tutorials/mathml/advanced-formatting and let me know what you think?

**Comment by MMercieca** [comment]
- [x] Add a test

**Comment by MMercieca** [comment]
@bnbeckwith I don't think this equation was properly constructed--- a common problem with our DOCX -> HTML conversion.  I played around with adding a space before the `mtext` nodes, but what I ended up with was '  i  f  x=5` which I think is less readable than what we have now. 

I think the root problem is that the letters were entered as individual text nodes. `text()` should return the entire word, which would be fine here.  But it's not.  I tried merging adjacent `mtext` and `mspace` nodes, but I couldn't fit that in to the current stylesheets.

What do you think about moving forward with this as it at least renders in the final document?

**Comment by bnbeckwith** [comment]
@MMercieca, I think it's fine to move forward.

I agree that the current spacing is better than introducing weird spacing.

**Pull request merged**
